import { Notification } from '@academy/interfaces';

export const notifications: Notification[] = [
  {
    id: 'ntf_001',
    recipientId: 'stu_001',
    type: 'in-app',
    subject: 'Welcome to Academy Hub',
    message: 'Your learning workspace is ready.',
    status: 'sent',
    createdAt: '2026-02-10T09:00:00.000Z',
  },
  {
    id: 'ntf_002',
    recipientId: 'stu_002',
    type: 'email',
    subject: 'Course Enrollment Confirmation',
    message: 'You have been enrolled in Modern TypeScript.',
    status: 'sent',
    createdAt: '2026-02-11T09:00:00.000Z',
  },
  {
    id: 'ntf_003',
    recipientId: 'stu_003',
    type: 'sms',
    subject: 'Assignment Due Soon',
    message: 'Your Applied Statistics assignment is due in 2 days.',
    status: 'sent',
    createdAt: '2026-02-12T09:00:00.000Z',
  },
  {
    id: 'ntf_004',
    recipientId: 'stu_004',
    type: 'in-app',
    subject: 'New Grade Posted',
    message: 'Your Quantum Physics Fundamentals grade is now available.',
    status: 'sent',
    createdAt: '2026-02-13T09:00:00.000Z',
  },
  {
    id: 'ntf_005',
    recipientId: 'stu_005',
    type: 'email',
    subject: 'Course Reminder',
    message: 'Don\'t forget about your Molecular Biology lecture today.',
    status: 'sent',
    createdAt: '2026-02-14T09:00:00.000Z',
  },
  {
    id: 'ntf_006',
    recipientId: 'stu_006',
    type: 'in-app',
    subject: 'System Maintenance',
    message: 'Scheduled maintenance tonight from 2-4 AM.',
    status: 'sent',
    createdAt: '2026-02-15T09:00:00.000Z',
  },
  {
    id: 'ntf_007',
    recipientId: 'stu_007',
    type: 'sms',
    subject: 'Library Book Available',
    message: 'The book you requested is now available for pickup.',
    status: 'sent',
    createdAt: '2026-02-16T09:00:00.000Z',
  },
  {
    id: 'ntf_008',
    recipientId: 'stu_008',
    type: 'email',
    subject: 'Event Invitation',
    message: 'You are invited to the guest lecture on Organic Chemistry.',
    status: 'sent',
    createdAt: '2026-02-17T09:00:00.000Z',
  },
  {
    id: 'ntf_009',
    recipientId: 'stu_009',
    type: 'in-app',
    subject: 'Feedback Requested',
    message: 'Please share your thoughts on the Creative Writing Workshop.',
    status: 'sent',
    createdAt: '2026-02-18T09:00:00.000Z',
  },
  {
    id: 'ntf_010',
    recipientId: 'stu_010',
    type: 'sms',
    subject: 'Payment Received',
    message: 'Your tuition payment for World History Survey has been processed.',
    status: 'sent',
    createdAt: '2026-02-19T09:00:00.000Z',
  },
];