import { Course } from '@academy/interfaces';

export const courses: Course[] = [
  {
    id: 'cou_001',
    title: 'Modern TypeScript',
    description: 'Build reliable services and applications with modern TypeScript.',
    credits: 4,
    teacherId: 'tea_001',
    status: 'published',
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'cou_002',
    title: 'Applied Statistics',
    description: 'Practical statistics for data-informed decisions.',
    credits: 3,
    teacherId: 'tea_002',
    status: 'published',
    createdAt: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'cou_003',
    title: 'Quantum Physics Fundamentals',
    description: 'Introduction to quantum mechanics and particle physics.',
    credits: 4,
    teacherId: 'tea_003',
    status: 'published',
    createdAt: '2026-02-15T09:00:00.000Z',
  },
  {
    id: 'cou_004',
    title: 'Molecular Biology',
    description: 'Study of biological activity at the molecular level.',
    credits: 3,
    teacherId: 'tea_004',
    status: 'published',
    createdAt: '2026-03-01T09:00:00.000Z',
  },
  {
    id: 'cou_005',
    title: 'Organic Chemistry',
    description: 'Structure, properties, and reactions of organic compounds.',
    credits: 4,
    teacherId: 'tea_005',
    status: 'published',
    createdAt: '2026-03-15T09:00:00.000Z',
  },
  {
    id: 'cou_006',
    title: 'Creative Writing Workshop',
    description: 'Develop your writing skills through practice and feedback.',
    credits: 3,
    teacherId: 'tea_006',
    status: 'published',
    createdAt: '2026-04-01T09:00:00.000Z',
  },
  {
    id: 'cou_007',
    title: 'World History Survey',
    description: 'Overview of major historical events and civilizations.',
    credits: 3,
    teacherId: 'tea_007',
    status: 'published',
    createdAt: '2026-04-15T09:00:00.000Z',
  },
  {
    id: 'cou_008',
    title: 'Digital Art and Design',
    description: 'Create art using digital tools and software.',
    credits: 4,
    teacherId: 'tea_008',
    status: 'published',
    createdAt: '2026-05-01T09:00:00.000Z',
  },
  {
    id: 'cou_009',
    title: 'Music Theory and Composition',
    description: 'Learn the fundamentals of music theory and create original compositions.',
    credits: 3,
    teacherId: 'tea_009',
    status: 'published',
    createdAt: '2026-05-15T09:00:00.000Z',
  },
  {
    id: 'cou_010',
    title: 'Introduction to Psychology',
    description: 'Basic concepts and theories of human behavior and mental processes.',
    credits: 3,
    teacherId: 'tea_010',
    status: 'published',
    createdAt: '2026-06-01T09:00:00.000Z',
  },
];