import { Teacher } from '@academy/interfaces';

export const teachers: Teacher[] = [
  {
    id: 'tea_001',
    firstName: 'Jordan',
    lastName: 'Lee',
    email: 'jordan.lee@example.edu',
    department: 'Computer Science',
    specialties: ['TypeScript', 'Cloud architecture'],
    status: 'active',
  },
  {
    id: 'tea_002',
    firstName: 'Samira',
    lastName: 'Khan',
    email: 'samira.khan@example.edu',
    department: 'Mathematics',
    specialties: ['Statistics', 'Machine learning'],
    status: 'active',
  },
  {
    id: 'tea_003',
    firstName: 'Alex',
    lastName: 'Chen',
    email: 'alex.chen@example.edu',
    department: 'Physics',
    specialties: ['Quantum mechanics', 'Thermodynamics'],
    status: 'active',
  },
  {
    id: 'tea_004',
    firstName: 'Maria',
    lastName: 'Garcia',
    email: 'maria.garcia@example.edu',
    department: 'Biology',
    specialties: ['Genetics', 'Molecular biology'],
    status: 'active',
  },
  {
    id: 'tea_005',
    firstName: 'David',
    lastName: 'Wilson',
    email: 'david.wilson@example.edu',
    department: 'Chemistry',
    specialties: ['Organic chemistry', 'Biochemistry'],
    status: 'active',
  },
  {
    id: 'tea_006',
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.anderson@example.edu',
    department: 'English Literature',
    specialties: ['Creative writing', 'Literary analysis'],
    status: 'active',
  },
  {
    id: 'tea_007',
    firstName: 'Robert',
    lastName: 'Taylor',
    email: 'robert.taylor@example.edu',
    department: 'History',
    specialties: ['World history', 'Political science'],
    status: 'active',
  },
  {
    id: 'tea_008',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    email: 'jennifer.martinez@example.edu',
    department: 'Art',
    specialties: ['Digital art', 'Graphic design'],
    status: 'active',
  },
  {
    id: 'tea_009',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.edu',
    department: 'Music',
    specialties: ['Music theory', 'Composition'],
    status: 'active',
  },
  {
    id: 'tea_010',
    firstName: 'Sarah',
    lastName: 'Davis',
    email: 'sarah.davis@example.edu',
    department: 'Psychology',
    specialties: ['Cognitive psychology', 'Behavioral analysis'],
    status: 'active',
  },
];